test_api_rest: fix return values
Tox fails on both tests with

        # missing message must lead to error
        rv = client.patch('/vm/my-vm-id')
>       assert rv.status_code == 400
E       assert 415 == 400
E        +  where 415 = <WrapperTestResponse streamed [415 UNSUPPORTED MEDIA TYPE]>.status_code

as we don't set the right content type. While setting it to application/json,
add another test that checks the 415 if _not_ set.

Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>